test:
  epochs: 100
  lr: 0.1
  gamma: 0.1
  scheduler: "exponential"
  batch_size: 256
  step_size: 10

old_run:
  epochs: 65
  lr: 0.1
  gamma: 0.8
  scheduler: "step"
  batch_size: 256
  step_size: 15
